version: 2.1

orbs:
    win: circleci/windows@5.0.0

jobs:
    build:
        machine: true
        resource_class: starport/chaosmod
        steps:
            - add_ssh_keys:
                fingerprints:
                  - "SHA256:Vez+9ng8BrMKVo1RJUa68647BVC9Rihu1rZVRiShbT4"
            - checkout
            - run: 
                name: Checkout Submodules
                command: |
                    git submodule sync
                    git submodule update --init --recursive
            - run:
                name: Download 7Zip
                command: |
                    & "C:\windows\system32\curl.exe" -L -o "${HOME}/7z.exe" "https://www.7-zip.org/a/7zr.exe"
            - restore_cache:
                name: Restoring VCPKG Cache
                key: vcpkg-build-{{ checksum "vcpkg.json" }}
            - restore_cache:
                name: Restore DX9 SDK Cache
                key: dx9-sdk
            - run: 
                name: Install Dependencies
                command: .ci\install-dependencies.ps1
            - save_cache:
                name: Caching DX9 SDK
                key: dx9-sdk
                paths:
                    - C:\Users\circleci\DirectXSDK
            - run: 
                name: Build Project
                command: .ci\build-project.ps1
                no_output_timeout: 25m
            - save_cache:
                name: Caching VCPKG Packages
                key: vcpkg-build-{{ checksum "vcpkg.json" }}
                paths:
                    - vcpkg_installed
            - run:
                name: Build Installer
                command: |
                    mkdir Release\EXE
                    Get-ChildItem -Path "Release" -Filter ".dll" -Recurse | Move-Item -Destination "Release\EXE" -Whatif
                    & ${HOME}/7z.exe a -r chaosmod.7z ./Release/* ./Assets/*
                    & "C:\Windows\System32\curl.exe" -o ./Installer/Assets/External/FreelancerHDESetup_v06_silent_test.exe https://f003.backblazeb2.com/b2api/v2/b2_download_file_by_id?fileId=4_z0d41f4d9e10a9adf85d20013_f212668fac620798a_d20240305_m125353_c003_v0312019_t0022_u01709643233941
                    Move-Item chaosmod.7z -Destination ./Installer/Assets/Mod
                    & C:\Users\circleci\Inno\iscc.exe /O+ ./Installer/setup.ics
                    & ${HOME}/7z.exe a -r Setup.7z ./Installer/Output*
                    Copy-Item ./Setup.7z -Destination C:\Users\circleci\artifacts\Setup.7z
                    Copy-Item ./Installer/Mod/chaosmod.7z -Destination C:\Users\circleci\artifacts\Assets.7z
            - run:
                name: " Release"
                command: 
                    mkdir C:\Users\circleci\artifacts
                    7z a -r 
                    7z a -r C:\Users\circleci\artifacts\ChaosMod.7z ./ChaosMod/Release/*
            - persist_to_workspace:
                root: C:\Users\circleci\artifacts
                paths: 
                    - ChaosMod.7z

    release:
        docker:
            - image: cibuilds/github:0.10
        steps:
            - attach_workspace:
                at: C:\Users\circleci\artifacts
            - run:
                name: Publish Release on GitHub
                command: |
                    VERSION=$(date +"%Y-%m-%d")
                    ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} C:\Users\circleci\artifacts

workflows:
    run-all:
        jobs:
            - build
            - release:
                requires:
                    - build

