version: 2.1

orbs:
    win: circleci/windows@5.0.0

jobs:
    windows-msvc:
        executor: win/server-2022
        steps:
            - add_ssh_keys:
                fingerprints:
                  - "SHA256:Vez+9ng8BrMKVo1RJUa68647BVC9Rihu1rZVRiShbT4"
            - checkout
            - run: 
                name: Install VCPKG
                command: .ci\install-vcpkg.ps1
            - run: 
                name: Install Dependencies
                command: .ci\install-dependencies.ps1
                no_output_timeout: 25m
            - run: 
                name: Build Project
                command: .ci\build-project.ps1

workflows:
    run-all:
        jobs:
            - windows-msvc