version: 2.1

orbs:
    win: circleci/windows@5.0.0

jobs:
    windows-msvc:
        executor: win/server-2022
        steps:
            - checkout
            - run: .ci\install-vcpkg.ps1
            - run: .ci\install-dependencies.ps1
            - run: .ci\build-project.ps1

workflows:
    run-all:
        jobs:
            - windows-msvc