name: Post Announcement
on:
  workflow_dispatch:
    inputs:
      date:
        description: A 'date' compatible string for which all releases should be included in the announcement.
        required: true
        type: string

jobs:
  discord:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - run: pip3 install requests

      - name: Get Release Notes
        run: python ${{ github.workspace }}/cli.py notes -d ${{ inputs.date }} -t ${{ github.token }}

      - name: Publish to Discord
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.DISCORD_ANNOUNCEMENT_WEBHOOK_URL }}
          embed-title: Chaos Mod Release Published!
          embed-url: ${{ env.URL }}
          embed-color: 65535
          embed-description: |
            Changelog:
            
            ${{ env.BODY }}