name: Post Announcement
on:
  workflow_run:
    workflows: [ nightly ]
    types: [ completed ]
  workflow_dispatch:

jobs:
  discord:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Get Latest Release
        id: version
        shell: bash
        run: |
          JSON=$(curl -L --silent \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ github.token }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/repos/TheStarport/ChaosMod/releases/latest" | \
            jq '{ "html_url", "body" }')
          URL=$(echo "$JSON" | jq -r '.["html_url"]')
          BODY=$(echo "$JSON" | jq -r '.["body"]')
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          echo "URL<<EOF" >> $GITHUB_ENV
          echo "$URL" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
          echo "BODY<<EOF" >> $GITHUB_ENV
          echo "$BODY" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Publish to Discord
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.DISCORD_ANNOUNCEMENT_WEBHOOK_URL }}
          embed-title: Chaos Mod Release Published!
          embed-url: ${{ env.URL }}
          embed-color: 65535
          embed-description: |
            Changelog:
            
            ${{ env.BODY }}